import 'package:json_annotation/json_annotation.dart';

part 'wearing_response.g.dart';

@JsonSerializable()
class WearingResponse {
  WearingResponse({
    required this.success,
    this.data,
  });

  bool success;
  List<WearingData>? data;

  factory WearingResponse.fromJson(Map<String, dynamic> json) =>
      _$WearingResponseFromJson(json);

  Map<String, dynamic> toJson() => _$WearingResponseToJson(this);
}

@JsonSerializable()
class WearingData {
  WearingData({
    required this.goodsNo,
    required this.goodsNmFl,
    required this.goodsNm,
    required this.goodsNmMain,
    required this.goodsNmList,
    required this.goodsNmDetail,
    required this.goodsNmPartner,
    required this.goodsDisplayFl,
    required this.goodsDisplayMobileFl,
    required this.goodsSellFl,
    required this.goodsSellMobileFl,
    required this.scmNo,
    required this.purchaseNo,
    required this.purchaseGoodsNm,
    required this.applyFl,
    required this.applyType,
    required this.applyMsg,
    required this.applyDt,
    required this.commission,
    required this.goodsCd,
    required this.cateCd,
    required this.goodsSearchWord,
    required this.goodsOpenDt,
    required this.goodsState,
    required this.goodsColor,
    required this.imageStorage,
    required this.imagePath,
    required this.brandCd,
    required this.makerNm,
    required this.originNm,
    required this.hscode,
    required this.goodsModelNo,
    required this.makeYmd,
    required this.launchYmd,
    required this.effectiveStartYmd,
    required this.effectiveEndYmd,
    required this.qrCodeFl,
    required this.goodsPermission,
    required this.goodsPermissionGroup,
    required this.goodsPermissionPriceStringFl,
    required this.goodsPermissionPriceString,
    required this.onlyAdultFl,
    required this.onlyAdultDisplayFl,
    required this.onlyAdultImageFl,
    required this.goodsAccess,
    required this.goodsAccessGroup,
    required this.goodsAccessDisplayFl,
    required this.goodsMustInfo,
    required this.kcmarkInfo,
    required this.taxFreeFl,
    required this.taxPercent,
    required this.cultureBenefitFl,
    required this.goodsWeight,
    required this.totalStock,
    required this.stockFl,
    required this.soldOutFl,
    required this.fixedSales,
    required this.fixedOrderCnt,
    required this.salesUnit,
    required this.minOrderCnt,
    required this.maxOrderCnt,
    required this.salesStartYmd,
    required this.salesEndYmd,
    required this.restockFl,
    required this.mileageFl,
    required this.mileageGroup,
    required this.mileageGoods,
    required this.mileageGoodsUnit,
    required this.mileageGroupInfo,
    required this.mileageGroupMemberInfo,
    required this.goodsBenefitSetFl,
    required this.benefitUseType,
    required this.newGoodsRegFl,
    required this.newGoodsDate,
    required this.newGoodsDateFl,
    required this.periodDiscountStart,
    required this.periodDiscountEnd,
    required this.goodsDiscountFl,
    required this.goodsDiscount,
    required this.goodsDiscountUnit,
    required this.fixedGoodsDiscount,
    required this.goodsDiscountGroup,
    required this.goodsDiscountGroupMemberInfo,
    required this.exceptBenefit,
    required this.exceptBenefitGroup,
    required this.exceptBenefitGroupInfo,
    required this.payLimitFl,
    required this.payLimit,
    required this.goodsPriceString,
    required this.goodsPrice,
    required this.fixedPrice,
    required this.costPrice,
    required this.optionFl,
    required this.optionDisplayFl,
    required this.optionName,
    required this.optionTextFl,
    required this.optionImagePreviewFl,
    required this.optionImageDisplayFl,
    required this.addGoodsFl,
    required this.addGoods,
    required this.shortDescription,
    required this.eventDescription,
    required this.goodsDescription,
    required this.goodsDescriptionMobile,
    required this.goodsDescriptionSameFl,
    required this.deliverySno,
    required this.relationFl,
    required this.relationSameFl,
    required this.relationCnt,
    required this.relationGoodsNo,
    required this.relationGoodsDate,
    required this.relationGoodsEach,
    required this.goodsIconStartYmd,
    required this.goodsIconEndYmd,
    required this.goodsIconCdPeriod,
    required this.goodsIconCd,
    required this.imgDetailViewFl,
    required this.externalVideoFl,
    required this.externalVideoUrl,
    required this.externalVideoWidth,
    required this.externalVideoHeight,
    required this.detailInfoDeliveryFl,
    required this.detailInfoDelivery,
    required this.detailInfoDeliveryDirectInput,
    required this.detailInfoASFl,
    required this.detailInfoAS,
    required this.detailInfoASDirectInput,
    required this.detailInfoRefundFl,
    required this.detailInfoRefund,
    required this.detailInfoRefundDirectInput,
    required this.detailInfoExchangeFl,
    required this.detailInfoExchange,
    required this.detailInfoExchangeDirectInput,
    required this.seoTagFl,
    required this.seoTagSno,
    required this.naverFl,
    required this.daumFl,
    required this.paycoFl,
    required this.naverImportFlag,
    required this.naverProductFlag,
    required this.naverAgeGroup,
    required this.naverGender,
    required this.naverTag,
    required this.naverAttribute,
    required this.naverCategory,
    required this.naverProductId,
    required this.memo,
    required this.orderCnt,
    required this.orderGoodsCnt,
    required this.hitCnt,
    required this.cartCnt,
    required this.wishCnt,
    required this.reviewCnt,
    required this.plusReviewCnt,
    required this.excelFl,
    required this.delFl,
    required this.regDt,
    required this.modDt,
    required this.delDt,
    required this.goodsVolume,
    required this.cremaReviewCnt,
    required this.naverReviewCnt,
    required this.naverNpayAble,
    required this.naverNpayAcumAble,
  });

  String goodsNo;
  String goodsNmFl;
  String goodsNm;
  String goodsNmMain;
  String goodsNmList;
  String goodsNmDetail;
  String goodsNmPartner;
  String goodsDisplayFl;
  String goodsDisplayMobileFl;
  String goodsSellFl;
  String goodsSellMobileFl;
  String scmNo;
  String? purchaseNo;
  String purchaseGoodsNm;
  String applyFl;
  String applyType;
  String? applyMsg;
  String? applyDt;
  String commission;
  String goodsCd;
  String cateCd;
  String goodsSearchWord;
  String goodsOpenDt;
  String goodsState;
  String goodsColor;
  String imageStorage;
  String imagePath;
  String brandCd;
  String makerNm;
  String originNm;
  String hscode;
  String goodsModelNo;
  String makeYmd;
  String launchYmd;
  String effectiveStartYmd;
  String effectiveEndYmd;
  String qrCodeFl;
  String goodsPermission;
  String goodsPermissionGroup;
  String goodsPermissionPriceStringFl;
  String goodsPermissionPriceString;
  String onlyAdultFl;
  String onlyAdultDisplayFl;
  String onlyAdultImageFl;
  String goodsAccess;
  String goodsAccessGroup;
  String goodsAccessDisplayFl;
  String goodsMustInfo;
  String kcmarkInfo;
  String taxFreeFl;
  String taxPercent;
  String cultureBenefitFl;
  String goodsWeight;
  String totalStock;
  String stockFl;
  String soldOutFl;
  String fixedSales;
  String fixedOrderCnt;
  String salesUnit;
  String minOrderCnt;
  String maxOrderCnt;
  String salesStartYmd;
  String salesEndYmd;
  String restockFl;
  String mileageFl;
  String mileageGroup;
  String mileageGoods;
  String mileageGoodsUnit;
  String mileageGroupInfo;
  String mileageGroupMemberInfo;
  String goodsBenefitSetFl;
  String benefitUseType;
  String newGoodsRegFl;
  String newGoodsDate;
  String newGoodsDateFl;
  String periodDiscountStart;
  String periodDiscountEnd;
  String goodsDiscountFl;
  String goodsDiscount;
  String goodsDiscountUnit;
  String fixedGoodsDiscount;
  String goodsDiscountGroup;
  String goodsDiscountGroupMemberInfo;
  String exceptBenefit;
  String exceptBenefitGroup;
  String exceptBenefitGroupInfo;
  String payLimitFl;
  String payLimit;
  String goodsPriceString;
  String goodsPrice;
  String fixedPrice;
  String costPrice;
  String optionFl;
  String optionDisplayFl;
  String optionName;
  String optionTextFl;
  String optionImagePreviewFl;
  String optionImageDisplayFl;
  String addGoodsFl;
  String addGoods;
  String shortDescription;
  String eventDescription;
  String goodsDescription;
  String goodsDescriptionMobile;
  String goodsDescriptionSameFl;
  String deliverySno;
  String relationFl;
  String relationSameFl;
  String relationCnt;
  String relationGoodsNo;
  String relationGoodsDate;
  String relationGoodsEach;
  String goodsIconStartYmd;
  String goodsIconEndYmd;
  String goodsIconCdPeriod;
  String goodsIconCd;
  String imgDetailViewFl;
  String externalVideoFl;
  String externalVideoUrl;
  String externalVideoWidth;
  String externalVideoHeight;
  String detailInfoDeliveryFl;
  String detailInfoDelivery;
  String detailInfoDeliveryDirectInput;
  String detailInfoASFl;
  String detailInfoAS;
  String detailInfoASDirectInput;
  String detailInfoRefundFl;
  String detailInfoRefund;
  String detailInfoRefundDirectInput;
  String detailInfoExchangeFl;
  String detailInfoExchange;
  String detailInfoExchangeDirectInput;
  String seoTagFl;
  String seoTagSno;
  String naverFl;
  String daumFl;
  String paycoFl;
  String naverImportFlag;
  String naverProductFlag;
  String naverAgeGroup;
  String naverGender;
  String naverTag;
  String naverAttribute;
  String naverCategory;
  String naverProductId;
  String memo;
  String orderCnt;
  String orderGoodsCnt;
  String hitCnt;
  String cartCnt;
  String wishCnt;
  String reviewCnt;
  String plusReviewCnt;
  String excelFl;
  String delFl;
  String regDt;
  String modDt;
  String delDt;
  String goodsVolume;
  String cremaReviewCnt;
  String naverReviewCnt;
  String naverNpayAble;
  String naverNpayAcumAble;

  factory WearingData.fromJson(Map<String, dynamic> json) =>
      _$WearingDataFromJson(json);

  Map<String, dynamic> toJson() => _$WearingDataToJson(this);
}
