// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi66f5Jh_3Fa_6hmhL8gma2gcNyD3BJV4',
    appId: '1:734030341278:android:9023945cd5b159037c478f',
    messagingSenderId: '734030341278',
    projectId: 'showny-fbd46',
    storageBucket: 'showny-fbd46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7MbfoDoH2OGaHlxGk0xFjQHScuwejhAo',
    appId: '1:734030341278:ios:50d266f41d6e12767c478f',
    messagingSenderId: '734030341278',
    projectId: 'showny-fbd46',
    storageBucket: 'showny-fbd46.appspot.com',
    androidClientId: '734030341278-q0610lh0qh27tbaf7a5mdhnnfe5u9ap6.apps.googleusercontent.com',
    iosClientId: '734030341278-37n8itt0914v5fssaor6vkih9on4n8tg.apps.googleusercontent.com',
    iosBundleId: 'com.showny.showny',
  );
}
